# Generated by Django 4.2.11 on 2024-07-06 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='itemwatch', to=settings.AUTH_USER_MODEL),
        ),
    ]
